import "./globals.css";
import { Libre_Baskerville, Source_Sans_Pro } from "next/font/google";

const libre = Libre_Baskerville({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-libre",
});
const source_sans_pro = Source_Sans_Pro({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-source",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${libre.variable} ${source_sans_pro.variable} bg-base-800 text-white`}
    >
      <body className="font-sans">{children}</body>
    </html>
  );
}
